# Generated by Django 5.0.1 on 2024-01-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_nutrition_nutritionitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionitems',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
